### ISSUE TITLE
Error while using RIFE/Models

### ISSUE THREAD

**Issue by SnowzNZ** [couleur-tweak-tips/smoothie-rs#13]
When attempting to use rife I get the following error:
```
ERR:

default_model_dir does not exist, expected: C:\Users\jackson\Downloads\smoothie-rs-bin-windows\models
Script evaluation failed:
Python exception:

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 2982, in vapoursynth._vpy_evaluate
  File "src\cython\vapoursynth.pyx", line 2983, in vapoursynth._vpy_evaluate
  File "C:\Users\jackson\Downloads\smoothie-rs-bin-windows\bin\jamba.vpy", line 108, in <module>
    raise NotADirectoryError()
NotADirectoryError

pipe:: Invalid data found when processing input
```

When trying to fix this error by adding the `models` folder into `./smoothie-rs-bin-windows`, I receive this error:
```
Script evaluation failed:
Python exception: name 'model_path' is not defined

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 2982, in vapoursynth._vpy_evaluate
  File "src\cython\vapoursynth.pyx", line 2983, in vapoursynth._vpy_evaluate
  File "C:\Users\jackson\Downloads\smoothie-rs-bin-windows\bin\jamba.vpy", line 111, in <module>
    model_path = path.join(model_path, pi['model'])
NameError: name 'model_path' is not defined

pipe:: Invalid data found when processing input
```

**Comment by SnowzNZ** [comment]
Heres a fix: https://www.youtube.com/watch?v=G5FYsxCm7GQ

**Comment by couleurm** [comment]
should this be closed since model paths have gotten overhauled?

**Comment by SnowzNZ** [comment]
If you wish to use RIFE pre interp, follow this guide: https://www.youtube.com/watch?v=G5FYsxCm7GQ
